name: Test Release

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  setup_matrix:
    uses: ./.github/workflows/setup-build-matrix.yml

  test_release:
    # if: "${{ contains(github.event.pull_request.labels.*.name, 'ci: test release') }}"
    needs: setup_matrix
    name: Test Release Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup_matrix.outputs.matrix).config }}
    steps:
      - name: Checkout Current Branch (Fast)
        uses: actions/checkout@v4

      - name: Install Correct Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Build
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: ${{matrix.features}} --release --target ${{ matrix.target }}
